module.exports = {
  "type": "category",
  "label": "2.3 Asynchrony and APIs",
  "items": [
    "intermediate-javascript/asynchrony-and-apis/2-3-0-1-asynchrony-and-apis-in-javascript-objectives",
    "intermediate-javascript/asynchrony-and-apis/2-3-0-2-asynchrony-in-javascript",
    "intermediate-javascript/asynchrony-and-apis/2-3-0-3-introduction-to-apis",
    "intermediate-javascript/asynchrony-and-apis/2-3-0-4-api-documentation-and-keys",
    "intermediate-javascript/asynchrony-and-apis/2-3-0-5-testing-api-calls-with-postman",
    "intermediate-javascript/asynchrony-and-apis/2-3-0-6-parsing-json",
    "intermediate-javascript/asynchrony-and-apis/2-3-0-7-making-api-calls-with-javascript",
    "intermediate-javascript/asynchrony-and-apis/2-3-0-8-protecting-api-keys",
    "intermediate-javascript/asynchrony-and-apis/2-3-0-9-exception-handling-for-api-calls",
    "intermediate-javascript/asynchrony-and-apis/2-3-0-10-the-devtools-network-tab",
    "intermediate-javascript/asynchrony-and-apis/2-3-0-11-javascript-exception-handling-with-try---catch",
    "intermediate-javascript/asynchrony-and-apis/2-3-1-1-openweather-api-giphy-api",
    "intermediate-javascript/asynchrony-and-apis/2-3-1-2-tools-for-handling-async-code",
    "intermediate-javascript/asynchrony-and-apis/2-3-1-3-introduction-to-promises",
    "intermediate-javascript/asynchrony-and-apis/2-3-1-4-promises-with-api-calls",
    "intermediate-javascript/asynchrony-and-apis/2-3-1-5-static-methods-and-properties",
    "intermediate-javascript/asynchrony-and-apis/2-3-1-6-separating-promise-logic",
    "intermediate-javascript/asynchrony-and-apis/2-3-1-7-sop-and-cors",
    "intermediate-javascript/asynchrony-and-apis/2-3-1-8-speaking-up",
    "intermediate-javascript/asynchrony-and-apis/2-3-2-1-api-refactor-dino-ipsum",
    "intermediate-javascript/asynchrony-and-apis/2-3-2-2-fetch-api",
    "intermediate-javascript/asynchrony-and-apis/2-3-2-3-async-and-await",
    "intermediate-javascript/asynchrony-and-apis/2-3-2-4-further-exploration-iifes",
    "intermediate-javascript/asynchrony-and-apis/2-3-3-1-bike-index-cryptocurrency-analytics-app-api-of-choice-longer-project",
    "intermediate-javascript/asynchrony-and-apis/2-3-3-2-further-exploration-chaining-promises",
    "intermediate-javascript/asynchrony-and-apis/2-3-3-3-pull-requests-and-submitting-great-work",
    "intermediate-javascript/asynchrony-and-apis/2-3-3-4-sprucing-up-your-github",
    "intermediate-javascript/asynchrony-and-apis/2-3-4-1-whiteboarding-practice-asynchrony",
    "intermediate-javascript/asynchrony-and-apis/2-3-5-1-asynchrony-and-apis-independent-project"
  ]
};