module.exports = {
  "type": "category",
  "label": "4.3 React with Redux",
  "items": [
    "react/react-with-redux/4-3-0-1-react-with-redux-objectives",
    "react/react-with-redux/4-3-0-2-introduction-to-redux",
    "react/react-with-redux/4-3-0-3-setting-up-our-first-project",
    "react/react-with-redux/4-3-0-4-writing-our-first-redux-test",
    "react/react-with-redux/4-3-0-5-writing-our-second-redux-test",
    "react/react-with-redux/4-3-0-6-writing-our-third-redux-test",
    "react/react-with-redux/4-3-0-7-anatomy-of-a-reducer",
    "react/react-with-redux/4-3-0-8-the-redux-store",
    "react/react-with-redux/4-3-0-9-redux-store-review",
    "react/react-with-redux/4-3-0-10-introduction-to-react-redux-library",
    "react/react-with-redux/4-3-0-11-adding-redux-to-react-part-1",
    "react/react-with-redux/4-3-0-12-adding-redux-to-react-part-2",
    "react/react-with-redux/4-3-0-13-adding-redux-to-react-part-3",
    "react/react-with-redux/4-3-1-1-redux-help-queue-project-refactor",
    "react/react-with-redux/4-3-1-2-combining-redux-reducers",
    "react/react-with-redux/4-3-1-3-adding-combined-reducers-to-react",
    "react/react-with-redux/4-3-1-4-building-a-react-application-with-redux-from-scratch",
    "react/react-with-redux/4-3-1-5-understanding-stereotype-threat",
    "react/react-with-redux/4-3-2-1-forum-word-puzzle-tic-tac-toe-three-day-project---part-1",
    "react/react-with-redux/4-3-2-2-action-creators",
    "react/react-with-redux/4-3-2-3-action-constants",
    "react/react-with-redux/4-3-2-4-hosting-a-react-project-with-gh-pages",
    "react/react-with-redux/4-3-3-1-forum-word-puzzle-tic-tac-toe-three-day-project---part-2-day-2",
    "react/react-with-redux/4-3-3-2-introduction-to-date-fns",
    "react/react-with-redux/4-3-3-3-component-lifecycle-methods",
    "react/react-with-redux/4-3-3-4-adding-wait-time-to-the-queue",
    "react/react-with-redux/4-3-3-5-adding-wait-time-to-the-queue-part-2",
    "react/react-with-redux/4-3-4-1-forum-word-puzzle-tic-tac-toe-three-day-project---part-3-day-3",
    "react/react-with-redux/4-3-4-2-technical-interview-practice-react-and-redux",
    "react/react-with-redux/4-3-4-3-whiteboard-practice",
    "react/react-with-redux/4-3-4-4-applying-for-jobs",
    "react/react-with-redux/4-3-5-1-react-with-redux-independent-project"
  ]
};