module.exports = {
  "type": "category",
  "label": "4.4 React with NoSQL",
  "items": [
    "react/react-with-nosql/4-4-0-1-react-with-nosql-objectives",
    "react/react-with-nosql/4-4-0-2-introduction-to-hooks-with-the-usestate-hook",
    "react/react-with-nosql/4-4-0-3-running-side-effects-with-the-useeffect-hook",
    "react/react-with-nosql/4-4-0-4-the-rules-of-hooks-custom-hooks-and-why-hooks-are-awesome",
    "react/react-with-nosql/4-4-0-5-refactoring-help-queue-to-use-hooks",
    "react/react-with-nosql/4-4-0-6-introduction-to-baas-firebase-and-firestore",
    "react/react-with-nosql/4-4-0-7-introduction-to-nosql",
    "react/react-with-nosql/4-4-0-8-the-cap-theorem-and-base",
    "react/react-with-nosql/4-4-0-9-setting-up-a-firebase-project-firestore-database-and-web-app",
    "react/react-with-nosql/4-4-0-10-firebase-documentation",
    "react/react-with-nosql/4-4-0-11-adding-firebase-to-react",
    "react/react-with-nosql/4-4-0-12-adding-tickets-to-firestore",
    "react/react-with-nosql/4-4-0-13-viewing-tickets-from-firestore",
    "react/react-with-nosql/4-4-0-14-updating-and-deleting-tickets-in-firestore",
    "react/react-with-nosql/4-4-0-15-structuring-data-in-firestore",
    "react/react-with-nosql/4-4-0-16-whiteboard-independent-project-overview",
    "react/react-with-nosql/4-4-0-17-whiteboard-evaluation-rubric",
    "react/react-with-nosql/4-4-0-18-a-guide-to-whiteboarding",
    "react/react-with-nosql/4-4-0-19-being-a-good-interviewer",
    "react/react-with-nosql/4-4-0-20-giving-constructive-feedback",
    "react/react-with-nosql/4-4-1-1-firestore-survey-quiz-of-choice-two-day-or-one-week-project",
    "react/react-with-nosql/4-4-1-2-client-side-routing",
    "react/react-with-nosql/4-4-1-3-react-router",
    "react/react-with-nosql/4-4-1-4-firebase-authentication",
    "react/react-with-nosql/4-4-1-5-firebase-authorization",
    "react/react-with-nosql/4-4-2-1-firestore-queries",
    "react/react-with-nosql/4-4-2-2-adding-wait-time-to-the-queue",
    "react/react-with-nosql/4-4-2-3-hosting-with-firebase",
    "react/react-with-nosql/4-4-3-1-choose-your-own-adventure-two-day-or-one-week-project",
    "react/react-with-nosql/4-4-3-2-styled-components",
    "react/react-with-nosql/4-4-3-3-further-exploration-opportunities",
    "react/react-with-nosql/4-4-3-4-informational-interviews",
    "react/react-with-nosql/4-4-4-1-technical-interview-practice-nosql",
    "react/react-with-nosql/4-4-4-2-resume-overview",
    "react/react-with-nosql/4-4-4-3-writing-your-resume",
    "react/react-with-nosql/4-4-5-1-react-with-nosql-independent-project"
  ]
};