module.exports = {
  "type": "category",
  "label": "4.2 React Fundamentals",
  "items": [
    "react/react-fundamentals/4-2-0-1-react-fundamentals-objectives",
    "react/react-fundamentals/4-2-0-2-introduction-to-react",
    "react/react-fundamentals/4-2-0-3-the-virtual-dom",
    "react/react-fundamentals/4-2-0-4-using-create-react-app",
    "react/react-fundamentals/4-2-0-5-react-components",
    "react/react-fundamentals/4-2-0-6-introduction-to-jsx",
    "react/react-fundamentals/4-2-0-7-planning-a-react-application",
    "react/react-fundamentals/4-2-0-8-building-a-static-site",
    "react/react-fundamentals/4-2-0-9-props",
    "react/react-fundamentals/4-2-0-10-prop-types",
    "react/react-fundamentals/4-2-0-11-looping-in-jsx",
    "react/react-fundamentals/4-2-0-12-using-external-stylesheets-with-react",
    "react/react-fundamentals/4-2-0-13-debugging-with-react-developer-tools",
    "react/react-fundamentals/4-2-0-14-adding-images",
    "react/react-fundamentals/4-2-1-1-help-queue-social-media-airbnb-clone",
    "react/react-fundamentals/4-2-1-2-introduction-to-state",
    "react/react-fundamentals/4-2-1-3-planning-our-application-part-2",
    "react/react-fundamentals/4-2-1-4-adding-local-state",
    "react/react-fundamentals/4-2-1-5-conditional-rendering",
    "react/react-fundamentals/4-2-1-6-updating-state-with-events",
    "react/react-fundamentals/4-2-1-7-binding-functions-in-react",
    "react/react-fundamentals/4-2-2-1-uuid-library",
    "react/react-fundamentals/4-2-2-2-adding-a-form",
    "react/react-fundamentals/4-2-2-3-unidirectional-data-flow",
    "react/react-fundamentals/4-2-2-4-passing-data-via-callbacks",
    "react/react-fundamentals/4-2-2-5-styling-react-css-objects",
    "react/react-fundamentals/4-2-3-1-help-queue-merch-site-event-logger",
    "react/react-fundamentals/4-2-3-2-overview-of-next-steps-adding-read-update-and-delete-functionality",
    "react/react-fundamentals/4-2-3-3-planning-our-application-part-3",
    "react/react-fundamentals/4-2-3-4-using-jsx-expressions-with-arguments",
    "react/react-fundamentals/4-2-3-5-showing-ticket-detail",
    "react/react-fundamentals/4-2-3-6-deleting-a-ticket",
    "react/react-fundamentals/4-2-3-7-reusing-components",
    "react/react-fundamentals/4-2-3-8-updating-a-ticket",
    "react/react-fundamentals/4-2-3-9-leveraging-linkedin",
    "react/react-fundamentals/4-2-4-1-help-queue-merch-site-event-logger-day-2",
    "react/react-fundamentals/4-2-4-2-technical-interview-preparation-react-fundamentals",
    "react/react-fundamentals/4-2-4-3-whiteboard-practice",
    "react/react-fundamentals/4-2-5-1-react-fundamentals-independent-project"
  ]
};