# this workflow is triggered manually, so the context is the repo from which it is run
name: Update curriculum

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Generate GitHub App token
        uses: peaceiris/actions-github-app-token@v1
        id: github-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.INSTALLATION_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Fetch docs and create docusaurus source directories for each track
        run: npm run fetch
        env:
          ORG: ${{ secrets.ORG }}
          INSTALLATION_TOKEN: ${{ steps.github-app-token.outputs.token }}

      - name: Build track
        run: cd ./tracks/${{ secrets.ORG }} && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ steps.github-app-token.outputs.token }}
          external_repository: ${{ secrets.ORG }}/lhtp-build
          publish_branch: gh-pages
          publish_dir: ./tracks/${{ secrets.ORG }}/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: 'Deploy to GitHub Pages'
