name: Find offline links & images

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: npm run find-broken-links
        env:
          NODE_ENV: 'production'
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          CC: ${{ secrets.CC }}
